// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Firebase n\'est pas configuré pour windows'
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase n\'est pas configuré pour windows linux'
        );
      default:
        throw UnsupportedError(
          'Firebase n\'est pas supporté',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5dAeGmNSDym7xDthf1GH66toTxQmoH8w',
    appId: '1:705752223630:android:204d8514e588fc608d5edf',
    messagingSenderId: '705752223630',
    projectId: 'cve-bar',
    storageBucket: 'cve-bar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtfwtCbubVEnvTH5jX-Donx2whEjkW2qY',
    appId: '1:705752223630:ios:2388fed626fa3bb28d5edf',
    messagingSenderId: '705752223630',
    projectId: 'cve-bar',
    storageBucket: 'cve-bar.firebasestorage.app',
    iosBundleId: 'com.example.barApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtfwtCbubVEnvTH5jX-Donx2whEjkW2qY',
    appId: '1:705752223630:ios:2388fed626fa3bb28d5edf',
    messagingSenderId: '705752223630',
    projectId: 'cve-bar',
    storageBucket: 'cve-bar.firebasestorage.app',
    iosBundleId: 'com.example.barApp',
  );
}
